language: python
python:
  - "3.6"
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/indigo_test
before_install:
  - "sudo apt-get install -y poppler-utils"
  - "rvm install ruby-2.6.2"
  - "rvm use ruby-2.6.2"
install: 
  - "pip install .[test]"
  - "bundle install"
  - "npm install -g jshint"
script: coverage run manage.py test && jshint indigo_app/static/javascript/indigo/
after_success:
  - coveralls
